language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.3.1 WP_MULTISITE=0
    - WP_VERSION=4.1.8 WP_MULTISITE=0
    - WP_VERSION=4.0.8 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=0
    - WP_VERSION=3.6 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
sudo: false
